-- 3.9
divisors :: Integer -> [Integer]
divisors n = filter (\d -> n `mod` d == 0) [1..n]

-- 3.10
intSqrRoot :: Integer -> Integer
intSqrRoot n = floor (sqrt (fromIntegral n))

isPrimeFast :: Integer -> Bool
isPrimeFast n = n > 1 && all(\d -> n `mod` d /= 0) [2..intSqrRoot(n)]

-- 3.11

-- a)
myappend :: [a] -> [a] -> [a]
myappend xs ys = foldr (:) ys xs

-- b)
myconcat :: [[a]] -> [a]
myconcat xss = foldr (++) [] xss

-- c)
reverseR :: [a] -> [a]
reverseR xs = foldr (\x acc -> acc ++ [x]) [] xs

-- d)
reverseL :: [a] -> [a]
reverseL xs = foldl (\ acc x -> x : acc ) [] xs


-- e)
myElem :: Eq a => a -> [a] -> Bool
myElem x xs = any(\n -> n == x)  xs


-- 3.12
fromBitsAccumulator :: [Int] -> Int -> Int
fromBitsAccumulator [] acc = acc 
fromBitsAccumulator (x : xs) acc = fromBitsAccumulator xs new_acc
    where 
        new_acc = (acc * 2) + x

fromBits :: [Int] -> Int
fromBits [] = 0
fromBits bits = fromBitsAccumulator bits 0

fromBitsHOF :: [Int] -> Int
fromBitsHOF bits = foldl(\ acc x -> (acc * 2) + x ) 0 bits

-- 3.13
group :: Eq a => [a] -> [[a]]
group [] = []
group (x : xs) = 
    let firstGroup = x : takeWhile(== x) xs
        rest  = dropWhile(== x) xs
    in firstGroup : group rest

-- 3.14
-- a)
intercalate :: a -> [a] -> [[a]]
intercalate n [] = [[n]]
-- Possibility A: The new element 'n' is placed at the front of the whole list.
-- Possibility B: The new element 'n' is inserted into ALL positions of the tail 'xs'.
-- We prepend the current head 'x' to every list generated by the recursive call.
intercalate n (x : xs) = (n : x : xs) :  map(\ ys -> x : ys) (intercalate n xs)

-- b)

permutations :: [a] -> [[a]]
permutations [] = [[]]
permutations (x : xs) = concatMap (intercalate x) (permutations xs)